import { ApolloProvider } from '@/components/ApolloProvider/ApolloProvider';
import './globals.css';
import Navbar from "@/components/Navber";
import Footer from "@/components/Footer";
import React, { Suspense } from 'react';
import LoadingSpinner from "@/components/Loading/LoadingSpinner";

export const metadata = {
    title: 'Real Estate',
    description: 'Generated by create next app',
};

const Layout = ({ children }: { children: React.ReactNode }) => {
    return (
        <html lang="en">
        <body>
        <ApolloProvider>
            <Suspense fallback={<LoadingSpinner />}>
                <Navbar/>
            </Suspense>
            {children}
            <Suspense fallback={<LoadingSpinner />}>
                <Footer/>
            </Suspense>
        </ApolloProvider>
        </body>
        </html>
    );
};

export default Layout;
